name: Update Submodule

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Submodule
        run: |
          git submodule update --remote --merge
          git add .
          git commit -m "Update submodule"
          git push
